version: '3.9'
services:
  api:
    container_name: api
    build: 
      context: ./api
      target: base
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/workspace:cached

  web:
    container_name: web
    build: 
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api
